language: php

sudo: false

matrix:
  include:
    - php: 7.0
      env: PARSE_CORE=1
    - php: 5.6
    - php: 5.5
    - php: 5.4
    - php: hhvm

before_install:
    # Setup WP_TESTS_DIR (needed to bootstrap WP PHPUnit tests). 
    - export WP_TESTS_DIR=/tmp/wordpress/tests/phpunit/
    # Clone the WordPress develop repo.
    - git clone --depth=1 --branch="4.1" git://develop.git.wordpress.org/ /tmp/wordpress/
    # Setup DB.
    - mysql -e "CREATE DATABASE wordpress_test;" -uroot
    # Setup wp-config.
    - cp /tmp/wordpress/wp-tests-config-sample.php /tmp/wordpress/wp-tests-config.php
    - sed -i "s/youremptytestdbnamehere/wordpress_test/" /tmp/wordpress/wp-tests-config.php
    - sed -i "s/yourusernamehere/root/" /tmp/wordpress/wp-tests-config.php
    - sed -i "s/yourpasswordhere//" /tmp/wordpress/wp-tests-config.php

install: composer install --no-dev

script:
  - phpunit

  # Parse WordPress core as a sanity check
  - if [[ "$PARSE_CORE" == "1" ]]; wget https://wordpress.org/latest.zip; fi
  - if [[ "$PARSE_CORE" == "1" ]]; unzip latest.zip; fi
  - if [[ "$PARSE_CORE" == "1" ]]; wp parser create wordpress --user=admin; fi

